---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: dapr
  namespace: default
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "15"
spec:
  interval: 10m0s
  url: https://dapr.github.io/helm-charts/
